### ISSUE TITLE
Docker image `0.4.0` actually contains `0.3.1` acme-dns-azure library

### ISSUE THREAD

**Issue by the-redback** [ZEISS/acme-dns-azure#132]
I was using docker image [`ghcr.io/zeiss/acme-dns-azure:0.4.0`](https://github.com/ZEISS/acme-dns-azure/pkgs/container/acme-dns-azure/252316243?tag=0.4.0) for workload_identity. 
But it was throwing error: 

```
strictyaml.exceptions.YAMLValidationError: while parsing a mapping
  in "<unicode string>", line 1, column 1:
    use_workload_identity_credentials ...
     ^ (line: 1)
unexpected key not in schema 'use_workload_identity_credentials'
```

After debugging, I found that, `0.4.0` container actually contains `0.3.1` acme-dns-azure library.

I have also tested with `edge` version, which is working properly.

**Comment by felixZdi** [comment]
Thanks for your feedback - currently working on a fix. The issue was caused by the cache of the container build for the package - old version was cached.

We will rebuild the tag **0.4.0** with the correct package.
